export const schema = `
CREATE TABLE IF NOT EXISTS cards (
  id TEXT PRIMARY KEY,
  oracle_id TEXT,
  multiverse_ids TEXT,
  mtgo_id INTEGER,
  mtgo_foil_id INTEGER,
  tcgplayer_id INTEGER,
  cardmarket_id INTEGER,
  name TEXT NOT NULL,
  lang TEXT,
  released_at TEXT,
  uri TEXT,
  scryfall_uri TEXT,
  layout TEXT,
  highres_image BOOLEAN,
  image_status TEXT,
  image_uris TEXT,
  mana_cost TEXT,
  cmc REAL,
  type_line TEXT,
  oracle_text TEXT,
  power TEXT,
  toughness TEXT,
  colors TEXT,
  color_identity TEXT,
  keywords TEXT,
  legalities TEXT,
  games TEXT,
  reserved BOOLEAN,
  finishes TEXT,
  oversized BOOLEAN,
  promo BOOLEAN,
  reprint BOOLEAN,
  variation BOOLEAN,
  set_id TEXT,
  \`set\` TEXT,
  set_name TEXT,
  set_type TEXT,
  set_uri TEXT,
  set_search_uri TEXT,
  scryfall_set_uri TEXT,
  rulings_uri TEXT,
  prints_search_uri TEXT,
  collector_number TEXT,
  digital BOOLEAN,
  rarity TEXT,
  card_back_id TEXT,
  artist TEXT,
  artist_ids TEXT,
  illustration_id TEXT,
  border_color TEXT,
  frame TEXT,
  frame_effects TEXT,
  security_stamp TEXT,
  full_art BOOLEAN,
  textless BOOLEAN,
  booster BOOLEAN,
  story_spotlight BOOLEAN,
  edhrec_rank INTEGER,
  penny_rank INTEGER,
  prices TEXT,
  related_uris TEXT,
  purchase_uris TEXT,
  card_faces TEXT,
  all_parts TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS decks (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  format TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS deck_cards (
  id TEXT PRIMARY KEY,
  deck_id TEXT NOT NULL,
  card_id TEXT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  is_sideboard BOOLEAN NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  FOREIGN KEY (deck_id) REFERENCES decks (id) ON DELETE CASCADE,
  FOREIGN KEY (card_id) REFERENCES cards (id) ON DELETE CASCADE
);
`;
